export enum NodeType {
  Add = "Add",
  And = "And",
  Assignment = "Assignment",
  AttributeExists = "AttributeExists",
  AttributeNotExists = "AttributeNotExists",
  AttributeType = "AttributeType",
  BeginsWith = "BeginsWith",
  Between = "Between",
  ConstantValue = "ConstantValue",
  Contains = "Contains",
  Equal = "Equal",
  GreaterOrEqual = "GreaterOrEqual",
  GreaterThan = "GreaterThan",
  IfNotExists = "IfNotExists",
  In = "In",
  LessOrEqual = "LessOrEqual",
  LessThan = "LessThan",
  ListAppend = "ListAppend",
  Name = "Name",
  Not = "Not",
  NotEqual = "NotEqual",
  Or = "Or",
  SetClause = "SetClause",
  Subtract = "Subtract",
  Size = "Size",
}
