export enum NodeType {
  And = "And",
  AttributeExists = "AttributeExists",
  AttributeNotExists = "AttributeNotExists",
  AttributeType = "AttributeType",
  BeginsWith = "BeginsWith",
  Between = "Between",
  ConstantValue = "ConstantValue",
  Contains = "Contains",
  Equal = "Equal",
  GreaterOrEqual = "GreaterOrEqual",
  GreaterThan = "GreaterThan",
  In = "In",
  LessOrEqual = "LessOrEqual",
  LessThan = "LessThan",
  Name = "Name",
  Not = "Not",
  NotEqual = "NotEqual",
  Or = "Or",
  Size = "Size",
}
